config/routes.rb
ProjectManager::Application.routes.draw do

  root :to => "projects#index"

  resources :projects do
    resources :roles
  end

  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  has_many :roles
  has_many :projects, :through => :roles

  validates :first_name, :presence => true
  validates :last_name, :presence => true

  before_save :cleanup

  def name
    "#{first_name} #{last_name}"
  end

  private

  def cleanup
    self[:first_name] = self[:first_name].capitalize
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title
 
  has_many :roles, :dependent => :destroy

  validates :title, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :person_id, :project_id, :status_id, :title

  belongs_to :project
  belongs_to :person
  belongs_to :status

  validates :project_id, :presence => true  
  validates :person_id, :presence => true
  validates :status_id, :presence => true
  validates :title, :presence => true

  default_scope order("updated_at DESC")

  #attr_protected :project_id

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :position, :title

  default_scope order("position ASC")

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_filter :authenticate, :only => :show

  def index
    @people = [
         'luke-skywalker',
         'darth-vader'
      ]
  end

  def show
    @person = params[:id]
  end


  private

  def authenticate
    if params[:id] == "darth-vader"
      redirect_to people_url, :notice => "Page is restricted."
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
 
  respond_to :html

  def new
    @role = project.roles.new

    respond_with [project, @role]
  end

  def create
    @role = project.roles.new(params[:role])
    new_was_successful = @role.save

    respond_with [project, @role] do |format|
      format.html {
        if new_was_successful
          redirect_to(project_path(project), :notice => 'The role was created')
        else
          render 'new'
        end
      }
    end
  end

  def edit
    @role = project.roles.find(params[:id])
    
    respond_with [project, @role]
  end

  def update
    @role = project.roles.find(params[:id])
    update_was_successful = @role.update_attributes(params[:role])

    respond_with [project, @role] do |format|
      format.html {
        if update_was_successful
          redirect_to(project_path(project), :notice => "The role was saved")
        else
          render 'edit'
        end
      }
    end
  end

  def destroy
    role = project.roles.find(params[:id])
    if role.destroy
      flash[:notice] = 'The role was destroyed'
    else
      flash[:alert] = 'The role could not be destroyed'
    end

    respond_with [project, @role] do |format|
      format.html {
        redirect_to(project_path(project))
      }
    end
  end


  private

  def project
    @project ||= Project.find(params[:project_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_icon(icon_name, url_or_object, options={})
    options.merge!({ :class => "icon #{icon_name}" })

    link_to(image_tag("icons/#{icon_name}.png"),
            url_or_object,
            options)
  end

end

app/helpers/people_helper.rb
module PeopleHelper

  def project_title_links(project)
    content_tag :h1 do
      [ project.title,
        link_to_icon('show', project),
        link_to_icon('edit', edit_project_path(project)),
        link_to_icon('destroy', project, {
          :confirm => 'Are you sure?',
          :method => :delete
        })
      ].join(' ').html_safe
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManager</title>
  <%= stylesheet_link_tag    "scaffold", "formtastic", "formtastic_changes", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %><p id="notice"><%= notice %></p><% end %>
<% if alert %><p id="alert"><%= alert %></p><% end %>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>People</h1>

<ul>
<% @people.each do |person| %>
    <li><%= link_to person, person_path(person) %><li>
<% end %>
</ul>

app/views/people/show.html.erb
<h1>Show template</h1>

<%= @person %>

<p><%= link_to "List of People", people_path %></p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project">
  <%= project_title_links(project) %>

  <%= render project.roles %>

  <p class="addlink">
    <%= link_to 'Add a new role', new_project_role_path(project) %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<header>
  <p>Projects</p>
</header>

<p class="addlink">
  <%= link_to 'Create a New Project', new_project_path %>
</p>

<%= render @projects %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<%= render @project %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/roles/_form.html.erb
<%= semantic_form_for [@role.project, @role] do |form| %>
  <%= form.inputs "Role" do %>
    <%= form.input :title %>        
    <%= form.input :person %>
    <%= form.input :status, :as => :radio %>
  <% end %>
  <%= form.buttons %>
<% end %>

app/views/roles/_role.html.erb
<div class="role">
  <div class="person-name"><%= role.person.name %></div>
  <div class="role-title"><%= role.title %></div>
  <div class="status-title <%= dom_id(role.status) %>"><%= role.status.title %>
  </div>
  <div class="time" datetime="<%= role.updated_at %>"><%=
role.updated_at.to_formatted_s(:short) %></div>

  <%= link_to_icon 'edit', edit_project_role_path(role.project, role) %>

  <%= link_to_icon 'destroy', project_role_path(role.project, role),
      :confirm => "Do you want to delete '#{role.person.name}, #{role.title}'?",
      :method => :delete %>
</div>

app/views/roles/edit.html.erb
<header>
  <p>Edit Role for: <%= @role.project.title %></p>
</header>

<%= render :partial => 'form' %>
<%= link_to "Back to Project", project_path(@role.project) %>

app/views/roles/new.html.erb
<header>
  <p>New Role for: <%= @role.project.title %></p>
</header>

<%= render :partial => 'form' %>